### ISSUE TITLE
Missing project build support

### ISSUE THREAD

**Issue by sandrobonazzola** [arcalot/arcaflow-plugin-utilities#6]
## Describe the bug

```console
$ poetry build
Building arcaflow-plugin-utilities (0.1.0)
```

and

```console
$ python -m build
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (poetry-core)
* Getting dependencies for sdist...
* Building sdist...
Traceback (most recent call last):
  File "~/upstream/arcaflow-plugin-utilities/venv/lib64/python3.9/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "~/upstream/arcaflow-plugin-utilities/venv/lib64/python3.9/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "~/upstream/arcaflow-plugin-utilities/venv/lib64/python3.9/site-packages/pep517/in_process/_in_process.py", line 302, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "/tmp/build-env-6f5je3ze/lib/python3.9/site-packages/poetry/core/masonry/api.py", line 76, in build_sdist
    path = SdistBuilder(poetry).build(Path(sdist_directory))
  File "/tmp/build-env-6f5je3ze/lib/python3.9/site-packages/poetry/core/masonry/builders/builder.py", line 83, in __init__
    self._module = Module(
  File "/tmp/build-env-6f5je3ze/lib/python3.9/site-packages/poetry/core/masonry/utils/module.py", line 69, in __init__
    raise ModuleOrPackageNotFound(
poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package arcaflow-plugin-utilities

ERROR Backend subprocess exited when trying to invoke build_sdist
```

building support is needed in order to publish to pypi.

**Comment by dustinblack** [comment]
Tested, and builds work now from `:main`
